# Alacritty Configuration (TOML format)

[window]
# Set the window padding
padding = { x = 10, y = 10 }
# Set the window decorations (full, none, transparent, buttonless)
decorations = "full"
# Dynamic title
dynamic_title = true

[font]
# Font family (standard monospace font for macOS and Linux)
normal = { family = "source code pro", style = "Bold" }
# Font size
size = 16.0

[colors]
# Gruvbox theme colors
[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.normal]
black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

[cursor]
# Cursor style (Block, Underline, Beam)
style = "Block"
unfocused_hollow = true

[mouse]
# Enable mouse mode
hide_when_typing = true

[scrolling]
# Scrollback buffer size (number of lines)
history = 10000
multiplier = 3

[keyboard]
bindings = [
  # Paste with Ctrl+Shift+V
  { key = "V", mods = "Control|Shift", action = "Paste" },
  
  # Copy with Ctrl+Shift+C
  { key = "C", mods = "Control|Shift", action = "Copy" },
  
  # Quit with Ctrl+Shift+Q
  { key = "Q", mods = "Control|Shift", action = "Quit" },
]


